# Generated by Django 3.0.7 on 2020-06-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, null=True)),
                ('time', models.TimeField()),
                ('done', models.BooleanField(blank=True, default=False, null=True)),
                ('important', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
